### ISSUE TITLE
Uncaught abort: Cannot enlarge memory arrays

### ISSUE THREAD

**Issue by asanchezgomez** [jayralencar/sqlite-cipher.js#4]
Hi!

I've found another issue with 0.3.0 version, but I don't know in which part of my code it happens:

```
[25470:0403/105700:INFO:CONSOLE(68)] "Uncaught abort("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 16777216, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which adjusts the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ") at Error
    at Error (native)
    at Ra (/myapp/node_modules/sql.js/js/sql.js:32:124)
    at Qa (/myapp/node_modules/sql.js/js/sql.js:32:22)
    at p (/myapp/node_modules/sql.js/js/sql.js:488:103)
    at Function.l.ba (/myapp/node_modules/sql.js/js/sql.js:12:164)
    at Ia (/myapp/node_modules/sql.js/js/sql.js:397:297)
    at _Q (/myapp/node_modules/sql.js/js/sql.js:465:135615)
    at Array.Iu (/myapp/node_modules/sql.js/js/sql.js:468:26931)
    at sO (/myapp/node_modules/sql.js/js/sql.js:465:55965)
    at _f (/myapp/node_modules/sql.js/js/sql.js:459:91456)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.", source: /myapp/node_modules/sqlite-sync/sqlite.js (68)
```
In the previous version it does not happen.

**Comment by jayralencar** [comment]
Hi!
I think that is problem with memory. 
Try:
Open **sqlite-cipher/node_modules/sql.js/js/sql.js**, find for ```oa=r.TOTAL_MEMORY||16777216```. And change to ```oa=r.TOTAL_MEMORY||536870912``` for 512 MB.

If does not work, [Look it](https://github.com/kripken/sql.js/issues/113).

**Comment by asanchezgomez** [comment]
Okey thanks! I will try this solution ASAP and I will let you know the result. Are you going to include this modification in the next version?

Best regards.

**Comment by jayralencar** [comment]
Have you had any result?

**Comment by asanchezgomez** [comment]
Hi!

I'm working on Windows and I don't have this path: **sqlite-cipher/node_modules/sql.js/js/sql.js**
I have this one: **sqlite-cipher\node_modules\sqlite-sync\node_modules\sql.js\js\sql.js**, but I don't know if it is the same.

**Comment by jayralencar** [comment]
Yes, It's the same!

**Comment by asanchezgomez** [comment]
Okey, and instead of `oa=r.TOTAL_MEMORY||16777216` I have `na=f.TOTAL_MEMORY||16777216`. Therefore, I have to change to `na=f.TOTAL_MEMORY||536870912` . It is correct?

**Comment by jayralencar** [comment]
Yes.

**Comment by asanchezgomez** [comment]
Okey, I've changed it thirty minutes ago and it is still working without any problems. In the new version, 0.3.1, is changed this value?

**Comment by jayralencar** [comment]
Not yet. But I'm studying a way to rebuild sql.js to change this value in the installation.

**Comment by asanchezgomez** [comment]
okey thank you!

**Comment by asanchezgomez** [comment]
Hi @jayralencar ! Have you fixed this issue in the new 0.3.2 version?

Thanks!

**Comment by jayralencar** [comment]
No!

**Comment by asanchezgomez** [comment]
Okey thank you! Let me know when you fix it please :)

**Comment by jayralencar** [comment]
Ok!

**Comment by asanchezgomez** [comment]
Hi! I think that we have to keep open this issue until it is definitely fixed in order to keep it in mind :)
